name: Test stop-scan

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build GitHub Action
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v4
      - name: Install action dependencies
        working-directory: stop-scan
        run: npm ci && npm install -g @vercel/ncc
      - name: Build release
        working-directory: stop-scan
        run: npm run build && npm run pack
      - name: Copy files to release
        run: |
          mkdir -p release
          cp stop-scan/README.md release/
          cp stop-scan/action.yml release/
          cp -R stop-scan/dist/ release/dist/
      - name: Bright Security Scan 🏁
        id: scan
        uses: NeuraLegion/bright-github-actions/run-scan@release
        with:
          api_token: ${{ secrets.BRIGHT_TOKEN }}
          hostname: ${{ vars.HOSTNAME }}
          name: GitHub scan ${{ github.sha }}
          discovery_types: |
            [ "crawler" ]
          module: "dast"
          crawler_urls: |
            [ "https://brokencrystals.com" ]
          hosts_filter: |
            [ ]
      - name: Stop the scan 🛑
        id: stop
        uses: ./release
        with:
          api_token: ${{ secrets.BRIGHT_TOKEN }}
          hostname: ${{ vars.HOSTNAME }}
          scan: ${{ steps.scan.outputs.id }}
