name: Run-scan Automated testing

on: [workflow_dispatch]

jobs:
  release:
    name: Build GitHub Action
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./run-scan
        run: npm ci && npm install -g @vercel/ncc

      - name: Build release
        working-directory: ./run-scan
        run: npm run build && npm run pack

      - name: Bright Security Scan 🏁
#        working-directory: ./run-scan
        uses: ./run-scan
        with:
          api_token: ${{ secrets.BRIGHT_TOKEN }}
          name: GitHub scan ${{ github.sha }}
          discovery_types: |
            [ "crawler" ]
          crawler_urls: |
            [ "https://brokencrystals.com" ]
          module: "dast"
          hosts_filter: |
            [ ]
