name: Test run-scan

on:
  pull_request:
    branches:
      - '**'

jobs:
  release:
    name: Build GitHub Action
    runs-on: ubuntu-latest
    container: node:20
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci && npm install -g @vercel/ncc
    - name: Build release
      run: npm run build && npm run pack
    - name: Copy files to release
      run: |
        mkdir release
        cp README.md release/
        cp action.yml release/
        cp -R dist/ release/dist/
    - name: Bright Security Scan 🏁
      uses: ./release
      with:
        api_token: ${{ secrets.BRIGHT_TOKEN }}
        name: GitHub scan ${{ github.sha }}
        discovery_types: |
          [ "crawler" ]
        crawler_urls: |
          [ "https://brokencrystals.com" ]
        module: "dast"
        hosts_filter: |
          [ ]
